### ISSUE TITLE
runtime error Cannot read property 'trim' of undefined

### ISSUE THREAD

**Issue by lumpov** [gr3p1p3/transparent-proxy#3]
in some requests I see this error in console:

```
### 2021-03-25T09:52:20.160Z 192.168.88.249:58655 TypeError: Cannot read property 'trim' of undefined
    at parseHeaders (/home/pi/Development/proxy/node_modules/transparent-proxy/lib/parseHeaders.js:22:54)
    at Socket.onDataFromClient (/home/pi/Development/proxy/node_modules/transparent-proxy/ProxyServer.js:175:41)
    at Socket.emit (events.js:193:13)
    at addChunk (_stream_readable.js:295:12)
    at readableAddChunk (_stream_readable.js:276:11)
    at Socket.Readable.push (_stream_readable.js:231:10)
    at TCP.onStreamRead (internal/stream_base_commons.js:154:17)
```

**Comment by gr3p1p3** [comment]
Fixed!
