### ISSUE TITLE
Responses w/o headers crash the proxy

### ISSUE THREAD

**Issue by wwerner** [gr3p1p3/transparent-proxy#33]
If an HTTP server returns a response without headers (which is legal, response headers are optional [according to the spec](https://www.w3.org/Protocols/rfc2616/rfc2616-sec6.html#sec6)), the proxy crashes.

## Steps to reproduce on `v1.12.2`

1. Use the following `index.js` file to spin up a server on `:8080`: `npm install transparent-proxy && node index.js`

index.js
```js
const ProxyServer = require('transparent-proxy');
const server = new ProxyServer({verbose:true});
server.listen(8080, '0.0.0.0', function () {
    console.log('TCP-Proxy-Server started!', server.address());
});
```

2. Mock an http server on `:8000` that returns `200 OK` w/o headers: `while true; do echo "HTTP/1.1 200 OK\r\n\r\n" | nc -l 8000; done`

3. Make a request to the mock HTTP server through the proxy: `curl -vvv http://localhost:8000 --proxy localhost:8080`

## Result

Expected: The empty response is returned

Actual:

The proxy crashes with 
```
node_modules/transparent-proxy/core/HttpMessage.js:88
        if (this._data?.headers['content-length'] && this.body) {
                               ^

TypeError: Cannot read properties of undefined (reading 'content-length')
    at Response.parseData (/private/tmp/crash/node_modules/transparent-proxy/core/HttpMessage.js:88:32)
    at Session.set response [as response] (/private/tmp/crash/node_modules/transparent-proxy/core/Session.js:158:28)
    at Socket.onDataFromUpstream (/private/tmp/crash/node_modules/transparent-proxy/core/onConnectedClientHandling.js:95:37)
    at Socket.emit (node:events:513:28)
    at addChunk (node:internal/streams/readable:315:12)
    at readableAddChunk (node:internal/streams/readable:289:9)
    at Socket.Readable.push (node:internal/streams/readable:228:10)
    at TCP.onStreamRead (node:internal/stream_base_commons:190:23)
```

## Analysis

This happens b/c in `Response.parseData` it is assumed that [headers are present](https://github.com/gr3p1p3/transparent-proxy/blob/master/core/HttpMessage.js#L88) (`if (this._data?.headers['content-length'] && this.body) {`) but `HttpMessage#parseData` does not [set it to an empty object if no headers are present](https://github.com/gr3p1p3/transparent-proxy/blob/master/lib/parseDataToObject.js#L22). If there are no header lines, the `headers` field is never initialized.

## Fix

Either make access to headers optional.
```diff
--- a/HttpMessage.js
+++ b/HttpMessage.js
@@ -88,7 +88,7 @@ class Response extends HttpMessage {
     super.parseData(buffer, true);
 
     // TODO this will not work for every response
-    if (this._data?.headers["content-length"] && this.body) {
+    if (this._data?.headers?.["content-length"] && this.body) {
       const bodyBytes = Buffer.byteLength(this.body);
       this.complete =
         parseInt(this._data.headers["content-length"]) <= bodyBytes;
```

Or initialize headers with an empty object in any case when parsing the message

```diff
+++ b/parseDataToObject.js
@@ -13,7 +13,9 @@ module.exports = function parseDataToObject(data, isResponse = false, chunked =
     const DOUBLE_CRLF = CRLF + CRLF;
     const dataString = data.toString();
     const splitAt = dataString.indexOf(DOUBLE_CRLF); //TODO split at LF and delete CR after instead doing this
-    const infoObject = {};
+    const infoObject = {
+        headers: {}
+    };
 
     if (!chunked) {
         let [headers, body] = [dataString.slice(0, splitAt), dataString.slice(splitAt + DOUBLE_CRLF.length)];
@@ -38,7 +40,6 @@ module.exports = function parseDataToObject(data, isResponse = false, chunked =
                 }
             }
             else {
-                infoObject.headers = infoObject.headers || {};
                 const splitIndexRow = headerRow.indexOf(SEPARATOR);
                 const [attribute, value] = [headerRow.slice(0, splitIndexRow), headerRow.slice(splitIndexRow + 1)];
                 if (attribute && value) {
```

**Comment by wwerner** [comment]
Second fix option is implemented in https://github.com/gr3p1p3/transparent-proxy/pull/34
